// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Grade } from "./Grade";

export type GuessResult = { grade: Array<Grade>, };
